language: java
jdk:
  - openjdk8

branches:
  only:
    - master

befor_install:
 - chmod +x mvnw

before_deploy:
  - zip -r spring-project-groupware *
  - mkdir -p deploy
  - mv spring-project-groupware.zip deploy/spring-project-groupware.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-project-groupware # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: KingHyunSu/groupware #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-project-groupware # S3 버킷
    key: spring-project-groupware.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: spring-project-groupware # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: project-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: KingHyunSu/groupware
      branch: master
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kailking611@gmail.com 
